services:
  app:
    image: shinsenter/laravel:php8.4-nginx
    ports:
      - "8010:80"
    volumes:
      - ./:/var/www/html
    environment:
      APP_USER: "tirtaraharja"
      APP_GROUP: "tirtaraharja"
      APP_UID: 1001
      APP_GID: 1001
